services:
  postgres-pizzashop:
    image: bitnami/postgresql
    hostname: postgres-pizzashop
    container_name: postgres-pizzashop
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pizzashop
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d pizzashop"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PGHOST=postgres-pizzashop
      - PGPORT=5432
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pizzashop
      - API_BASE_URL=http://localhost:3333
      - AUTH_REDIRECT_URL=http://localhost:3000
      - JWT_SECRET_KEY=pizzashopsecret
      - RESEND_API_KEY=your_resend_api_key_here
    ports:
      - 3333:3333
    depends_on:
      postgres-pizzashop:
        condition: service_healthy
    command: sh -c "bun install --frozen-lockfile && bun run migrate && bun run seed && bun run dev"

volumes:
  postgres_data:
